### PR TITLE
Hello Microverse project setting up linters

### PR DESCRIPTION
**Pull request by sibabalwemosia24**
### Description
Hello Microverse project to set up linters for HTML and CSS

## General Requirements

- Document work in a professional way
- Make sure there are no linter errors
- Use the correct Gitflow
- Make sure irrelevant files are ignored by Git

### CODE REVIEW

**Review by codecaiine — CHANGES_REQUESTED** [review]
Hi @sibabalwemosia24 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good use of Github flow :heavy_check_mark: 
- Great commits messages :heavy_check_mark: 

## Required Changes ♻️
#### PLEASE APPLY THIS REQUIREMENT CAREFULLY CAUSE I CAN NOT USE INLINE COMMENTS

- [ ]  I noticed that you have a lot of empty files because you missed the project requirements Please follow carefully [the project requirements ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md). It is very important for the developer to peer attention to detail a give a completed project :smile: 
- [ ] Please add the `node_modules` directory and `test.md` to the .gitignore file. It's a good practice to add the node_modules to the .gitignore. It will help you to avoid a big size of dependencies in your repository. :smile:   
- [ ] Please edit your Pull Request to make it a more descriptive t, it should tell what changes are inside to the reviewer . A good example will be **Set up a Hello Microverse project** instead of  **My First pull request**  :+1: 
- [ ] Please edit also your Pull Request summary because like your PR title the summary should describe introduced changes in more detail. :+1: 
You can check the example below :arrow_down: 
Screenshot from 2022-08-16 18-25-08
- [ ] Please add a descriptive README file to your project by using [this template](https://github.com/microverseinc/readme-template) provide by microverse and please customize it to your project because it is important to keep your project profession :smile: 
- [ ] Please don't forget to add a license to your project and I recommend using the [MIT license](https://choosealicense.com/licenses/mit/), Set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). another resource is [any other license](https://choosealicense.com/licenses/) . :smile: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sibabalwemosia24** [comment]
### Description
Hello Microverse project to set up linters for HTML and CSS
##General Requirements

- Document work in a professional way
- Make sure there are no linter errors
- Use the correct Gitflow
- Make sure irrelevant files are ignored by Git

**Review by sumairq — CHANGES_REQUESTED** [review]
Hi @sibabalwemosia24 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow

## Required Changes ♻️

- [ ] As mentioned by the previous reviewer, kindly add a Pull request description, which explains the changes introduced in the pull request. Your pull request description is empty kindly edit and add a description. Cheers :+1:

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by aimemalaika — APPROVED** [review]
Hi @sibabalwemosia24 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tugsem** [comment]
Hi @sibabalwemosia24 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 🔴 🔴 

You have submitted the previous project's link. Please use the right Pull Request link related to Portfolio: setup and mobile first

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
